import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    ManyToOne,
} from 'typeorm';
import { Scenario } from './scenario.entity';

@Entity('guest_plays')
export class GuestPlay {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column()
    guestId: string; // Anonymous UUID generated by client

    @Column()