import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    ManyToOne,
} from 'typeorm';
import { Scenario } from './scenario.entity';

@Entity('guest_plays')
export class GuestPlay {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column()
    guestId: string; // Anonymous UUID generated by client

    @Column()
    scenarioId: string;

    @ManyToOne(() => Scenario)
    scenario: Scenario;

    @Column('jsonb')
    choicesLog: any; // Log of all decisions made

    @Column('float')
    finalScore: number;

    @Column({ nullable: true })
    completedAt: Date;

    @Column({ type: 'jsonb', nullable: true })
    metadata: any; // Device info, browser, etc.

    @CreateDateColumn()
    createdAt: Date;
}
