export enum BadgeCategory {
    GAMEPLAY = 'GAMEPLAY',
    VERIFICATION = 'VERIFICATION',
    COMMUNITY = 'COMMUNITY',
    ACHIEVEMENT = 'ACHIEVEMENT',
    PROGRESSION = 'PROGRESSION',
    COMPETITIVE = 'COMPETITIVE',
}
