export enum PlayerActionType {
  NEXT = 'NEXT',
  CHOICE = 'CHOICE',
  INPUT = 'INPUT',
  FINISH = 'FINISH',
  VERIFY = 'VERIFY',
  SHARE = 'SHARE',
  IGNORE = 'IGNORE',
  REPORT = 'REPORT',
  INVESTIGATE = 'INVESTIGATE',
  FACT_CHECK = 'FACT_CHECK',
}
