export enum ReportStatus {
  NEW = 'NEW',
  UNDER_REVIEW = 'UNDER_REVIEW',
  NEEDS_COMMUNITY_REVIEW = 'NEEDS_COMMUNITY_REVIEW',
  NEEDS_MORE_EVIDENCE = 'NEEDS_MORE_EVIDENCE',
  VERIFIED_FALSE = 'VERIFIED_FALSE',
  VERIFIED_TRUE = 'VERIFIED_TRUE',